/**
 * 🧬 Genoma Installer - Environment File Generator
 * Generates .env files for dev and production modes
 */

export interface EnvConfig {
  mode: 'dev' | 'production';
  provider: string;
  apiKey: string;
  channels: string[];
  pgaEnabled: boolean;
  gatewayToken?: string;
}

export function generateEnvFile(config: EnvConfig): string {
  const gatewayToken = config.gatewayToken || generateToken();
  const timestamp = new Date().toISOString();

  const lines: string[] = [
    '# 🧬 Genoma Configuration',
    '# Auto-generated by Genoma Installer',
    `# Mode: ${config.mode}`,
    `# Date: ${timestamp}`,
    '',
    '# === Core ===' ,
    `NODE_ENV=${config.mode === 'dev' ? 'development' : 'production'}`,
    `GENOMA_DEV_MODE=${config.mode === 'dev'}`,
    `GENOMA_LOG_LEVEL=${config.mode === 'dev' ? 'debug' : 'info'}`,
    '',
    '# === Gateway ===',
    `GENOMA_GATEWAY_TOKEN=${gatewayToken}`,
    'GENOMA_GATEWAY_PORT=18789',
    `GENOMA_GATEWAY_BIND=${config.mode === 'dev' ? 'localhost' : 'lan'}`,
    '',
    '# === AI Provider ===',
  ];

  // Add API Key based on provider
  switch (config.provider) {
    case 'openai':
      lines.push(`OPENAI_API_KEY=${config.apiKey}`);
      break;
    case 'anthropic':
      lines.push(`ANTHROPIC_API_KEY=${config.apiKey}`);
      break;
    case 'google':
      lines.push(`GEMINI_API_KEY=${config.apiKey}`);
      break;
    case 'ollama':
      lines.push('# Using local Ollama models');
      lines.push('OLLAMA_BASE_URL=http://localhost:11434');
      break;
    default:
      if (config.apiKey) {
        lines.push(`# Provider: ${config.provider}`);
        lines.push(`API_KEY=${config.apiKey}`);
      }
  }

  // PGA Config
  lines.push('');
  lines.push('# === PGA (Evolución) ===');
  lines.push(`PGA_ENABLED=${config.pgaEnabled}`);

  if (config.mode === 'dev') {
    lines.push('PGA_VERBOSE_LOGGING=true');
    lines.push('PGA_AUTO_MUTATION=false');
    lines.push('PGA_STORAGE_TYPE=memory');
  } else {
    lines.push('PGA_VERBOSE_LOGGING=false');
    lines.push('PGA_AUTO_MUTATION=true');
    lines.push('PGA_AUTO_ROLLBACK=true');
    lines.push('PGA_STORAGE_TYPE=database');
  }

  // Channels
  if (config.channels.length > 0) {
    lines.push('');
    lines.push('# === Channels ===');
    lines.push('# Configure your channel tokens below');

    if (config.channels.includes('telegram')) {
      lines.push('# TELEGRAM_BOT_TOKEN=123456:ABC...');
    }
    if (config.channels.includes('discord')) {
      lines.push('# DISCORD_BOT_TOKEN=...');
    }
    if (config.channels.includes('slack')) {
      lines.push('# SLACK_BOT_TOKEN=xoxb-...');
      lines.push('# SLACK_APP_TOKEN=xapp-...');
    }
    if (config.channels.includes('whatsapp')) {
      lines.push('# WhatsApp uses QR pairing - no token needed');
    }
  }

  // Development extras
  if (config.mode === 'dev') {
    lines.push('');
    lines.push('# === Development ===');
    lines.push('GENOMA_HOT_RELOAD=true');
    lines.push('GENOMA_VERBOSE=true');
    lines.push('DEBUG=genoma:*');
  }

  return lines.join('\n') + '\n';
}

export function generateDevEnv(config: Omit<EnvConfig, 'mode'>): string {
  return generateEnvFile({ ...config, mode: 'dev' });
}

export function generateProdEnv(config: Omit<EnvConfig, 'mode'>): string {
  return generateEnvFile({ ...config, mode: 'production' });
}

function generateToken(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let token = '';
  for (let i = 0; i < 32; i++) {
    token += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return token;
}
